var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                    o                                           ",
   "                                          o o                                   ",
   "                                         xxxxx                                  ",
   "                                o                                               ",
   "                              xxxxx                                             ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                      xxxx                                 ooo                  ",
   "               xxxxx                                      xxxxx                 ",
   "               x                                          xxxxx                 ",
   "     @     xxxxx   o o  d              d                  xxxxx         o o     ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                               x!!!!x    x!!!!!!!!!x                            ",
   "                               x!!!!x    x!!!!!!!!!x                            ",
   "                               x!!!!x    x!!!!!!!!!x                            ",
   "                               xxxxxx    xxxxxxxxxxx                            ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
["                                                                                     ",
"                                                                                      ",
"                                                                                      ",
"                                                        xxxxxxxxx                     ",
"                                                        x!!!!!!!x                     ",
"                                                        x!!!!!!!x                     ",
"                                                        x!!!!!!!x                     ",
"                                                         x!!!!!x                      ",
"                                                          xvvvx                       ",
"                 xxxxxxx                                                             ",
"                 x!!!!!x                                                              ",
"                 x!!!!!x                                                              ",
"                 x!!!!!x                                                              ",
"                  x!v!x                                                               ",
"  @                                                  o     o      o                   ",
" xxxxxxxx                                          xxxxxxxxxxxxxxxxxxx                ",
"                                                                                      ",
"          o o                                                                         ",
"        xxxxxxxx                     o  o  o                                  o  o    ",
"                                    xxxxxxxxxxxx                           xxxxxxxx   ",
"                 o  o                                                                 ",
"               xxxxxxxx           xx                                xxx               ",
"                                                                                      ",
"                              d                          o   o                        ",
"                          xxxxxxxxx                   xxxxxxxxxxxx                    ",
"                                                                                      ",
"                                                                                      ",
"                                                                                      ",
"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],


  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                  o                                           ",
   "                                                                 xxx                                          ",
   "                                     d         o    o                                  o       o              ",
   " xxx      o    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "         xxx                                                  x!!!!!!!x                                       ",
   "                                                               xv!!!vx                                        ",
   "                                                                                                              ",
   "         d                                                                                                    ",
   "    xxxxxxxxxxxx                                                                                              ",
   "                                                                                                              ",
   "                   o      o     o                                                                             ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        ",
   "                                                |!!!!!!|                                                      ",
   "                                                                                     xx=             xx       ",
   "                                                                                             o o              ",
   "                                                                                            xxxxx             ",
   "                                                                                                              ",
   "                                                                                     xx=             xx       ",
   "                                            d                o    o                                           ",
   " xxxxxxxxxx      xx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                  x!!!!!x                                          |!!!!|                            x!!!!!x  ",
   "                  x!!!!!x                                                                             x!v!x   ",
   "         o        x!!!!!x                                                                                     ",
   "       xxxxx      xxxxxxx                                                                                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "      d                            o                       d                  o            o                o ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         xxx",
   "                                                                                                              ",
   "                                                                                                      xxxx    ",
   "                                                                                                              ",
   "   @                  o          o     o      o                            o          o            o          ",
   "xxxxxxxxxxxxxxxxxx   xxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
